# development:
#   adapter: async

# test:
#   adapter: async

# production:
#   adapter: redis
#   url: redis://localhost:6379/1

default: &default
adapter: redis
url: redis://localhost:6379/1

development:
  <<: *default

test:
  <<: *default

production:
  adapter: redis
  url: 'redis://myappredis.wpef5k.0001.usw2.cache.amazonaws.com:6379/0'
